name: llama_cpp_example
description: A sample command-line application.
version: 1.0.0

environment:
  sdk: '>=3.0.0 <3.2.0'

dependencies:
  llama_cpp:
    path: ..

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
