name: llama_cpp
description: A dart binding for llama.cpp library, bringing AI to dart world.
version: 1.2.0
repository: https://github.com/lindeer/llama-cpp

topics:
  - ai
  - nlp
  - llm

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.3
  native_assets_cli: ^0.8.0

dev_dependencies:
  ffigen: ^11.0.0
  lints: ^3.0.0
  test: ^1.21.0
