name: llama_cpp
description: A dart binding for llama.cpp library, bringing AI to dart world.
version: 0.9.0
repository: https://github.com/lindeer/llama-cpp

environment:
  sdk: '>=3.0.0 <3.2.0'

dependencies:
  ffi: ^2.1.0
  native_assets_cli: ^0.1.0
  native_toolchain_c: ^0.1.0

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  test: ^1.21.0
