name: llama_cpp
description: A dart binding for llama.cpp library, bringing AI to dart world.
version: 1.0.0
repository: https://github.com/lindeer/llama-cpp

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  ffi: ^2.1.0
  native_assets_cli: ^0.4.2
  native_toolchain_c: ^0.3.4

dev_dependencies:
  ffigen: ^8.0.2
  lints: ^3.0.0
  test: ^1.21.0
