name: rag
description: An example of RAG (Retrieval Augment Generation) app.
version: 1.0.0
publish_to: none

environment:
  sdk: ^3.3.0

dependencies:
  chromadb: ^0.1.2
  llama_cpp:
    path: ../..
  uuid: ^4.3.3

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
